seo: 
  site_name: 
  title: 
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username:
alert_banner:
  display: true
  alert_message: Black Friday Sale - 30% Off All Products